services:
    PrestaShop\Module\PsFixturesCreator\Command\ShopCreatorCommand:
        class: PrestaShop\Module\PsFixturesCreator\Command\ShopCreatorCommand
        tags:
            - { name: 'console.command' }