services:
    Faker\Generator:
      factory: ['PrestaShop\Module\PsFixturesCreator\Faker\FakerFactory', 'create']
      arguments:
        - 'en_EN'

    PrestaShop\Module\PsFixturesCreator\Creator\CustomerCreator:
      arguments:
        $faker: '@Faker\Generator'

    PrestaShop\Module\PsFixturesCreator\Creator\CartCreator:
      arguments:
        $faker: '@Faker\Generator'

    PrestaShop\Module\PsFixturesCreator\Creator\CartRuleCreator:
      arguments:
        $faker: '@Faker\Generator'

    PrestaShop\Module\PsFixturesCreator\Creator\ProductCreator:
      arguments:
        $faker: '@Faker\Generator'

    PrestaShop\Module\PsFixturesCreator\Creator\OrderCreator:
      arguments:
        $faker: '@Faker\Generator'
        $customerCreator: '@PrestaShop\Module\PsFixturesCreator\Creator\CustomerCreator'
        $cartCreator: '@PrestaShop\Module\PsFixturesCreator\Creator\CartCreator'

    PrestaShop\Module\PsFixturesCreator\Creator\AttributeCreator:
      arguments:
        $entityManager: '@doctrine.orm.entity_manager'
        $langRepository: '@prestashop.core.admin.lang.repository'
        $shopRepository: '@prestashop.core.admin.shop.repository'
        $faker: '@Faker\Generator'

    PrestaShop\Module\PsFixturesCreator\Creator\ProductCombinationCreator:
      arguments:
        $entityManager: '@doctrine.orm.entity_manager'
        $commandBus: '@prestashop.core.command_bus'

    PrestaShop\Module\PsFixturesCreator\Command\ShopCreatorCommand:
        class: PrestaShop\Module\PsFixturesCreator\Command\ShopCreatorCommand
        arguments:
          $customerCreator: '@PrestaShop\Module\PsFixturesCreator\Creator\CustomerCreator'
          $cartCreator: '@PrestaShop\Module\PsFixturesCreator\Creator\CartCreator'
          $orderCreator: '@PrestaShop\Module\PsFixturesCreator\Creator\OrderCreator'
          $cartRuleCreator: '@PrestaShop\Module\PsFixturesCreator\Creator\CartRuleCreator'
          $productCreator: '@PrestaShop\Module\PsFixturesCreator\Creator\ProductCreator'
          $attributeCreator: '@PrestaShop\Module\PsFixturesCreator\Creator\AttributeCreator'
          $productCombinationCreator: '@PrestaShop\Module\PsFixturesCreator\Creator\ProductCombinationCreator'
        tags:
            - { name: 'console.command' }
