services:
    Faker\Generator:
      factory: ['Faker\Factory', 'create']
      arguments:
        - 'en_EN'

    PrestaShop\Module\PsFixturesCreator\CustomerCreator:
      class: PrestaShop\Module\PsFixturesCreator\CustomerCreator
      arguments:
        $faker: '@Faker\Generator'

    PrestaShop\Module\PsFixturesCreator\CartCreator:
      class: PrestaShop\Module\PsFixturesCreator\CartCreator
      arguments:
        $faker: '@Faker\Generator'

    PrestaShop\Module\PsFixturesCreator\CartRuleCreator:
      class: PrestaShop\Module\PsFixturesCreator\CartRuleCreator
      arguments:
        $faker: '@Faker\Generator'

    PrestaShop\Module\PsFixturesCreator\ProductCreator:
      class: PrestaShop\Module\PsFixturesCreator\ProductCreator
      arguments:
        $faker: '@Faker\Generator'

    PrestaShop\Module\PsFixturesCreator\OrderCreator:
      class: PrestaShop\Module\PsFixturesCreator\OrderCreator
      arguments:
        $faker: '@Faker\Generator'
        $customerCreator: '@PrestaShop\Module\PsFixturesCreator\CustomerCreator'
        $cartCreator: '@PrestaShop\Module\PsFixturesCreator\CartCreator'

    PrestaShop\Module\PsFixturesCreator\ProductCombinationCreator:
      class: PrestaShop\Module\PsFixturesCreator\ProductCombinationCreator
      arguments:
        $entityManager: '@doctrine.orm.entity_manager'
        $commandBus: '@prestashop.core.command_bus'

    PrestaShop\Module\PsFixturesCreator\Command\ShopCreatorCommand:
        class: PrestaShop\Module\PsFixturesCreator\Command\ShopCreatorCommand
        arguments:
          $customerCreator: '@PrestaShop\Module\PsFixturesCreator\CustomerCreator'
          $cartCreator: '@PrestaShop\Module\PsFixturesCreator\CartCreator'
          $orderCreator: '@PrestaShop\Module\PsFixturesCreator\OrderCreator'
          $cartRuleCreator: '@PrestaShop\Module\PsFixturesCreator\CartRuleCreator'
          $productCreator: '@PrestaShop\Module\PsFixturesCreator\ProductCreator'
          $productCombinationCreator: '@PrestaShop\Module\PsFixturesCreator\ProductCombinationCreator'
        tags:
            - { name: 'console.command' }
